from django.urls import path

from . import views

urlpatterns = [
    # Global Admin URLs
    path(
        "admin/global/business/tiers/", views.TierListView.as_view(), name="tiers.list"
    ),
    path(
        "admin/global/business/tiers/create/",
        views.TierCreateView.as_view(),
        name="tiers.create",
    ),
    path(
        "admin/global/business/tiers/<int:pk>/",
        views.TierDetailView.as_view(),
        name="tiers.detail",
    ),
    path(
        "admin/global/business/tiers/<int:pk>/versions/<int:version_pk>/",
        views.TierVersionDetailView.as_view(),
        name="tiers.version_detail",
    ),
    path(
        "admin/global/business/tiers/<int:pk>/edit/",
        views.TierUpdateView.as_view(),
        name="tiers.edit",
    ),
    path(
        "admin/global/business/tiers/<int:pk>/draft/",
        views.TierNewDraftView.as_view(),
        name="tiers.draft",
    ),
    path(
        "admin/global/business/tiers/<int:pk>/publish/",
        views.TierPublishView.as_view(),
        name="tiers.publish",
    ),
    path(
        "admin/global/business/tiers/<int:pk>/archive/",
        views.TierArchiveView.as_view(),
        name="tiers.archive",
    ),
    path(
        "admin/global/business/subscriptions/",
        views.SubscriptionListView.as_view(),
        name="subscriptions.list",
    ),
    path(
        "admin/global/business/subscriptions/create/",
        views.SubscriptionCreateView.as_view(),
        name="subscriptions.create",
    ),
    path(
        "admin/global/business/subscriptions/<int:pk>/edit/",
        views.SubscriptionUpdateView.as_view(),
        name="subscriptions.edit",
    ),
    path(
        "admin/global/business/addons/",
        views.AddonDefinitionListView.as_view(),
        name="addons.list",
    ),
    path(
        "admin/global/business/addons/create/",
        views.AddonDefinitionCreateView.as_view(),
        name="addons.create",
    ),
    path(
        "admin/global/business/addons/<int:pk>/edit/",
        views.AddonDefinitionUpdateView.as_view(),
        name="addons.edit",
    ),
    path(
        "admin/global/business/addons/<int:pk>/toggle/",
        views.AddonDefinitionToggleActiveView.as_view(),
        name="addons.toggle",
    ),
    # Add-on Assignments
    path(
        "admin/global/business/addons/assignments/organizers/",
        views.OrganizerAddonListView.as_view(),
        name="addons.assignments.organizer.list",
    ),
    path(
        "admin/global/business/addons/assignments/organizers/create/",
        views.OrganizerAddonCreateView.as_view(),
        name="addons.assignments.organizer.create",
    ),
    path(
        "admin/global/business/addons/assignments/organizers/<int:pk>/edit/",
        views.OrganizerAddonUpdateView.as_view(),
        name="addons.assignments.organizer.edit",
    ),
    path(
        "admin/global/business/addons/assignments/events/",
        views.EventAddonListView.as_view(),
        name="addons.assignments.event.list",
    ),
    path(
        "admin/global/business/addons/assignments/events/create/",
        views.EventAddonCreateView.as_view(),
        name="addons.assignments.event.create",
    ),
    path(
        "admin/global/business/addons/assignments/events/<int:pk>/edit/",
        views.EventAddonUpdateView.as_view(),
        name="addons.assignments.event.edit",
    ),
    # Organizer URLs
    path(
        "control/organizer/<str:organizer>/business/plan/",
        views.OrganizerPlanView.as_view(),
        name="organizer.plan",
    ),
    path(
        "control/organizer/<str:organizer>/business/addons/<int:pk>/purchase/",
        views.OrganizerAddonPurchaseView.as_view(),
        name="organizer.addon.purchase",
    ),
]
