# Generated by Django 6.0.7 on 2026-09-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventyay_business", "0008_addon_definitions_and_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventaddon",
            name="capability",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Capability snapshot"
            ),
        ),
        migrations.AddField(
            model_name="eventaddon",
            name="currency",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="Currency snapshot"
            ),
        ),
        migrations.AddField(
            model_name="eventaddon",
            name="entitlement_value",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Entitlement value snapshot"
            ),
        ),
        migrations.AddField(
            model_name="eventaddon",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price snapshot",
            ),
        ),
        migrations.AddField(
            model_name="organizeraddon",
            name="capability",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Capability snapshot"
            ),
        ),
        migrations.AddField(
            model_name="organizeraddon",
            name="currency",
            field=models.CharField(
                blank=True, max_length=3, verbose_name="Currency snapshot"
            ),
        ),
        migrations.AddField(
            model_name="organizeraddon",
            name="entitlement_value",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Entitlement value snapshot"
            ),
        ),
        migrations.AddField(
            model_name="organizeraddon",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price snapshot",
            ),
        ),
    ]
