# Generated by Django 6.0.7 on 2026-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventyay_business",
            "0009_eventaddon_capability_eventaddon_currency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventaddon",
            name="cancel_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Cancel at"),
        ),
        migrations.AddField(
            model_name="eventaddon",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Canceled at"
            ),
        ),
        migrations.AddField(
            model_name="organizeraddon",
            name="cancel_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Cancel at"),
        ),
        migrations.AddField(
            model_name="organizeraddon",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Canceled at"
            ),
        ),
    ]
