# Generated by Django 6.0.7 on 2026-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventyay_business", "0010_addon_cancellation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="addondefinition",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe price ID"
            ),
        ),
        migrations.AddField(
            model_name="addondefinition",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe product ID"
            ),
        ),
        migrations.AddField(
            model_name="eventaddon",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Stripe payment intent ID",
            ),
        ),
        migrations.AddField(
            model_name="eventaddon",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Stripe subscription ID",
            ),
        ),
        migrations.AddField(
            model_name="organizeraddon",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Stripe payment intent ID",
            ),
        ),
        migrations.AddField(
            model_name="organizeraddon",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Stripe subscription ID",
            ),
        ),
    ]
