# Generated by Django 6.0.7 on 2026-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventyay_business", "0011_addondefinition_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventaddon",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="organizeraddon",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
