# Generated by Django 6.0.7 on 2026-09-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventyay_business",
            "0012_alter_eventaddon_status_alter_organizeraddon_status",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tier",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe product ID"
            ),
        ),
        migrations.AlterField(
            model_name="eventaddon",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="organizeraddon",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
