# Generated by Django 6.0.7 on 2026-09-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventyay_business",
            "0013_tier_stripe_product_id_alter_eventaddon_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="past_due_since",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Past due since"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pending_billing_interval",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                max_length=20,
                null=True,
                verbose_name="Pending billing interval",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pending_change_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Pending change at"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pending_tier_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_subscriptions",
                to="eventyay_business.tierversion",
                verbose_name="Pending tier version",
            ),
        ),
    ]
